### ISSUE TITLE
About check case for BooleanT class

### ISSUE THREAD

**Issue by crapper** [Jerrylum/ProtocolDiagram#4]
Problem:
I'm always frustrated when the BooleanT class can handle t and f but not for T and F. Furthermore, for the case like tRue or trUe.

Solution:
Isn't it will be better for do the s.toLowerCase() and just check on true and false is better? 
I can see the case itself wanted to solve some time ppl just all in lower or True or False in first letter of upper case. 
But this toLowerCase() just allow those extra cases like
TrUe or TRUE... can be also detacted.

If this idea is accepted, I also want to suggest to add s.contain("true") / s.contain("false") as the checking
Since there definitely will got some cases which the user wanted to type in "true" but mistype in "truee" or "rtrue".

**Comment by Jerrylum** [comment]
I see. I understand your idea, but I would use `String.equalsIgnoreCase` instead of `toLowerCase` if I were you.

After I did some testing, I think it would be better if we only accept `true` and `false` in case insensitive but not `t` and `f` in any cases. I also don't like the `contain` approach since it can be confused with string too. What do you think?
