### ISSUE TITLE
About Number not handling 0 value

### ISSUE THREAD

**Issue by crapper** [Jerrylum/ProtocolDiagram#5]
**Describe the bug**
Tried to parse a number code point buffer with content of 0, it return with null. 
Seems it is because of using PositiveInt instead of Int in the else checking after NegativeInt if statement.
Please kindly check on it.

**To Reproduce**
Number.parse(new CodePointBuffer("0")) will return null

**Expected behavior**
0 should be handled and stored in value

**Additional context**

**Comment by Jerrylum** [comment]
I see. This is a bug for sure. Please help me to fix it in your branch.

Also, I would like you to combine/merge branches `add-ZeroTest`, `add-MinusTest`, `add-DecimalTest`, `add-DigitTest`, `add-Digit1To9Test`, `add-IntTest`, `add-NegativeIntTest`, `add-PositiveIntTest`, `add-FracTest`, and `add-NumberTTest` into a branch `add-number-related-test` since there are too many branches. You don't need to submit a pull request in order to merge to `add-number-related-test`. After you merge all all the branches above, you can then sumbit a pull request to the Main. Thank you.
